name: timeframe_selector
description: "A widget for simple timeframe selection similar to calenders"
version: 0.2.2
repository: https://github.com/Cunibon/timeframe_selector

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
